[skip ci] Correction workflow release -> Typo sur STATUS

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -139,18 +139,18 @@ jobs:
           )
           if [ -z $RESPONSE ]
           then
-            echo "ERREUR: Réponse vide"
+            echo "::error::Réponse vide"
             exit 1
           fi
-          if ! echo $REPONSE | jq empty > /dev/null
+          if ! echo "$RESPONSE" | jq empty > /dev/null
           then
-            echo "ERREUR: JSON invalide"
+            echo "::error::JSON invalide"
             exit 1
           fi
-          $STATUS=$(echo $RESPONSE | jq -r '.status')
+          STATUS=$(echo "$RESPONSE" | jq -r '.status')
           if [ "$STATUS" != "success" ]
           then
-            echo "ERREUR: Failed to notify Packagist"
+            echo "::error::Failed to notify Packagist"
             echo "$RESPONSE"
             exit 1
           fi
